name: dcgp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2020.6.20
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - ncurses=6.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.10.0
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - bottle==0.12.19
    - charset-normalizer==2.0.9
    - colorama==0.4.4
    - conan==1.43.0
    - distro==1.6.0
    - fasteners==0.16.3
    - idna==3.3
    - jinja2==2.11.3
    - markupsafe==2.0.1
    - node-semver==0.6.1
    - patch-ng==1.17.4
    - pluginbase==1.0.1
    - pygments==2.10.0
    - pyjwt==1.7.1
    - python-dateutil==2.8.2
    - pyyaml==5.4.1
    - requests==2.26.0
    - six==1.16.0
    - tqdm==4.62.3
    - urllib3==1.26.7
